/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CorretorRouteImport } from './routes/corretor'
import { Route as DiretoriaRouteImport } from './routes/diretoria'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorRoute = CorretorRouteImport.update({
  id: '/corretor',
  path: '/corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaRoute = DiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OrcamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/corretor': typeof CorretorRoute
  '/diretoria': typeof DiretoriaRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendedor': typeof VendedorRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/corretor': typeof CorretorRoute
  '/diretoria': typeof DiretoriaRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendedor': typeof VendedorRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/corretor': typeof CorretorRoute
  '/diretoria': typeof DiretoriaRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendedor': typeof VendedorRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chamados'
    | '/configuracoes'
    | '/corretor'
    | '/diretoria'
    | '/orcamentos'
    | '/produtos'
    | '/reset-password'
    | '/vendedor'
    | '/orcamentos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chamados'
    | '/configuracoes'
    | '/corretor'
    | '/diretoria'
    | '/orcamentos'
    | '/produtos'
    | '/reset-password'
    | '/vendedor'
    | '/orcamentos/novo'
  id:
    | '__root__'
    | '/'
    | '/chamados'
    | '/configuracoes'
    | '/corretor'
    | '/diretoria'
    | '/orcamentos'
    | '/produtos'
    | '/reset-password'
    | '/vendedor'
    | '/orcamentos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChamadosRoute: typeof ChamadosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CorretorRoute: typeof CorretorRoute
  DiretoriaRoute: typeof DiretoriaRoute
  OrcamentosRoute: typeof OrcamentosRouteWithChildren
  ProdutosRoute: typeof ProdutosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VendedorRoute: typeof VendedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor': {
      id: '/corretor'
      path: '/corretor'
      fullPath: '/corretor'
      preLoaderRoute: typeof CorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria': {
      id: '/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof DiretoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof OrcamentosRoute
    }
  }
}

interface OrcamentosRouteChildren {
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
}

const OrcamentosRouteChildren: OrcamentosRouteChildren = {
  OrcamentosNovoRoute: OrcamentosNovoRoute,
}

const OrcamentosRouteWithChildren = OrcamentosRoute._addFileChildren(
  OrcamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChamadosRoute: ChamadosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CorretorRoute: CorretorRoute,
  DiretoriaRoute: DiretoriaRoute,
  OrcamentosRoute: OrcamentosRouteWithChildren,
  ProdutosRoute: ProdutosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VendedorRoute: VendedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
