/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiretoriaRouteImport } from './routes/diretoria'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VendedorRouteImport } from './routes/vendedor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaRoute = DiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diretoria': typeof DiretoriaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diretoria': typeof DiretoriaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diretoria': typeof DiretoriaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diretoria' | '/reset-password' | '/vendedor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diretoria' | '/reset-password' | '/vendedor'
  id: '__root__' | '/' | '/diretoria' | '/reset-password' | '/vendedor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiretoriaRoute: typeof DiretoriaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VendedorRoute: typeof VendedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria': {
      id: '/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof DiretoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiretoriaRoute: DiretoriaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VendedorRoute: VendedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
